apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    k8s-app: elasticsearch
data:
  cluster.name: es-cluster
  ES_PLUGINS: "https://download.support.siren.io/federate/7.13.4-25.1.zip"
  http.port: "9200"
  transport.port: "9300"
  network.host: "0.0.0.0"
  discovery.type: single-node
  xpack.graph.enabled: "false"
  xpack.ml.enabled: "false"
  xpack.monitoring.enabled: "false"
  xpack.security.enabled: "false"
  xpack.watcher.enabled: "false"