apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    k8s-app: elasticsearch
spec:
  type: NodePort
  selector:
    k8s-app: elasticsearch
  ports:
  - name: http
    port: 9200
    