apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-monitoring

bases:
  - elasticsearch
  - kibana
  - logstash

resources:
  - namespace.yaml
  - auditbeat-kubernetes.yaml
  - filebeat-kubernetes.yaml
  - heartbeat-kubernetes.yaml
  - metricbeat-kubernetes.yaml
