apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    k8s-app: kibana
data:
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  ELASTICSEARCH_HOSTS: '["http://elasticsearch-service:9200"]'
  xpack.graph.enabled: "false"
  xpack.ml.enabled: "false"
  xpack.monitoring.enabled: "false"
  xpack.security.enabled: "false"
  xpack.reporting.enabled: "false"